simplesocial/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

simplesocial/groups/urls.py
from django.urls import path
from groups import views

app_name = 'groups'

urlpatterns = [
    path('', views.ListGroups.as_view(), name='all'),
    path('create/', views.CreateGroup.as_view(), name='create'),
    path('posts/in/<slug:slug>', views.SingleGroup.as_view(), name='single'),
    path('join/<slug:slug>/', views.JoinGroup.as_view(), name='join'),
    path('leave/<slug:slug>/', views.LeaveGroup.as_view(), name='leave')
]

simplesocial/posts/urls.py
from django.urls import path, re_path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<str:username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<str:username>/<int:pk>/', views.PostDetailView.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views



urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('posts/', include('posts.urls')),
    path('groups/', include('groups.urls'))
]

simplesocial/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Star Social</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Russo+One&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">

</head>
<body>

    <nav class="navbar mynav" role="navigation" id="navbar">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Star Social</a>

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'posts:create' %}">Post</a></li>
                    <li><a href="{% url 'groups:all' %}">Groups</a></li>
                    <li><a href="{% url 'groups:create' %}">Create Group</a></li>   
                    <li><form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="logout-button" style="margin-top: 12px; color: black;">Logout</button>
                    </form></li>

                    {% else %}
                    <li><a href="{% url 'groups:all' %}">Groups</a></li>
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>

                    {% endif %}
                </ul>
        </div>
    </nav>

    <div class="container mycontent">

        {% block content %}
        {% endblock %}

    </div>

</body>
<canvas id="canvas"></canvas>
<script type="text/javascript" src="{% static 'simplesocial/js/master.js' %}"></script>
</html>

simplesocial/templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}

    <h1>Welcome to Star Social</h1>
    

{% endblock %}

simplesocial/templates/test.html
{% extends 'base.html' %}

{% block content %}

    <h1>You are now logged in!</h1>

{% endblock %}

simplesocial/templates/thanks.html
{% extends 'base.html' %}

{% block content %}

    <h1>Thanks for visiting, come back soon!</h1>

{% endblock %}